/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */
 
@interface WXCMagicBox : NSObject {
	BOOL _bRepeatSound;
	int _repeatPushModel;
	double _currTime;
	double _testTime;
}
@property(assign, nonatomic) BOOL bRepeatSound;
@property(assign, nonatomic) int repeatPushModel;
@property(assign, nonatomic) double testTime;
@property(assign, nonatomic) double currTime;
+(id)getThreadNameDic;
+(id)shareInstance;
-(void)otherOldCode;
-(BOOL)screenIsLocked;
-(id)getLockStateStr;
-(void)playDetectMuisc;
-(void)stopPlayCallSound;
-(void)playCallSoundBySysSound;
-(void)startPlayCallSound;
-(void)logMmeryUsed:(id)used;
-(void)logTestTimeLong:(id)aLong;
-(void)startTestTime;
-(void)stopVibrate;
-(void)shake;
-(void)triggerShake;
-(void)startVibrate;
-(void)didEnterBackgroundLong;
-(BOOL)isSilent;
-(void)stopPlayMute;
-(void)continuePlayMute;
-(void)playMute;
-(void)startDetectSilent;
-(void)volumeChanged:(id)changed;
-(void)removeHardKeyVolumeListener;
-(void)delayAddVolumeListener;
-(void)addHardKeyVolumeListener;
-(id)getDetectVolumeName;
-(id)getDetectVolumeNotifiName;
-(BOOL)threadNameIsRepeat:(id)repeat;
-(void)onSysConfigChanged:(id)changed;
-(id)init;
@end